version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t nicolaszelarayan/vacunarg-python:$CIRCLE_SHA1 .
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push Docker image to Docker Hub
          command: docker push nicolaszelarayan/vacunarg-python:$CIRCLE_SHA1
      - add_ssh_keys:
          fingerprints:
            - "3a:81:74:61:3b:6d:2e:e2:e8:42:5a:a7:66:b9:6e:5e"
      - run:
          name: SSH and Deploy
          command: |
            ssh -oStrictHostKeyChecking=no nicolas@$20.226.108.27 "docker pull nicolaszelaran/vacunarg-python:$CIRCLE_SHA1"
            ssh -oStrictHostKeyChecking=no nicolas@$20.226.108.27 "docker stop vacunarg-python || true"
            ssh -oStrictHostKeyChecking=no nicolas@$20.226.108.27 "docker rm vacunarg-python || true"
            ssh -oStrictHostKeyChecking=no nicolas@$20.226.108.27 "docker run -d -p 5000:5000 --name vacunarg-python nicolaszelaran/vacunarg-python:$CIRCLE_SHA1"
            

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
